name: NPM Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Publish Package to NPM Registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          dry-run: true

